version: '3.7'

services:
  client:
    container_name: client
    build: ./coffee-machine-client
    ports:
      - "4200:4200"
    environment:
      SHELL: /bin/bash
      NODE_ENV: development
    expose:
      - 4444
    volumes:
      - ./coffee-machine-client:/usr/src/app/client
      - /usr/src/app/client/node_modules
    entrypoint: ng serve --host 0.0.0.0 --poll 1

  server:
    container_name: server
    build:
      context: ./coffee-machine-server
      target: ${NODE_ENV}
    env_file:
      - ./envs/${NODE_ENV}.env
    volumes:
      - ./coffee-machine-server:/usr/src/app/server
      - /usr/src/app/server/node_modules
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
      - 9229:9229
    command: npm run start:dev
    networks:
      - webnet
    depends_on:
      - redis
      - postgres

  redis:
    container_name: ${REDIS_HOST}
    image: redis:5
    expose:
      - ${REDIS_PORT}:${REDIS_PORT}
    networks:
      - webnet
    volumes:
      - redis-data:/data
      - redis-conf:/usr/local/etc/redis/redis.conf

  postgres:
    container_name: ${DB_HOST}
    image: postgres:12
    networks:
      - webnet
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      PG_DATA: /var/lib/postgresql/data
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - pgdata:/var/lib/postgresql/data
networks:
  webnet:
volumes:
  pgdata:
  redis-data:
  redis-conf: